
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  #模版引擎配置
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: html5
  jackson:
    time-zone: Asia/Shanghai

  #数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/keyword?serverTimezone=Asia/Shanghai
    username: root
    password: 123
    # password: Admin123!
mybatis-plus:
  mapper-locations: "classpath:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lisk.keyword.pojo
logging:
  level:
    com.lisk.keyword.mapper : debug

